#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = map(int, input().split())
    k = [0]*M
    k_max = [0]*M
    a = [[]]*M
    for i in range(M):
        # k[i] = int(input())
        k_max[i] = int(input())
        a[i] = list(map(int, input().split()))
    # Failed to predict input format
    now = [[] for i in range(N+1)]
    next = []
    for i in range(M):
        now[a[i][k[i]]].append(i)
        if len(now[a[i][k[i]]]) == 2:
            next.append(a[i][k[i]])
    if not next:
        print(NO)
        exit()
    count = 0
    while next:

        count += 1
        if count == N:
            print(YES)
            exit()
        ne = next.pop()
        t1, t2 = now[ne]
        k[t1] += 1
        k[t2] += 1
        if k[t1] < k_max[t1]:
            now_t1 = a[t1][k[t1]]
            now[now_t1].append(t1)
            if len(now[now_t1]) == 2:
                next.append(now_t1)
        if k[t2] < k_max[t2]:
            now_t2 = a[t2][k[t2]]
            now[now_t2].append(t2)
            if len(now[now_t2]) == 2:
                next.append(now_t2)
    print(NO)
    exit()


if __name__ == '__main__':
    main()
