#!/usr/bin/env python3
import sys


def solve(N: int, X: int, S: str):
    for i in S:
        if i == 'o':
            X += 1
        elif i == 'x' and X >= 1:
            X -= 1
    return X


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    print(solve(N, X, S))

if __name__ == '__main__':
    main()
