#!/usr/bin/env python3


# Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
import heapq
from collections import deque


def main():
    # Failed to predict input format

    A = deque([])
    B = []
    heapq.heapify(B)
    sort_len = 0
    for i in range(int(input())):
        q = input().split()
        if q[0] == '1':
            x = int(q[1])
            A.append(x)

        elif q[0] == '2':
            if B:
                now = heapq.heappop(B)
                # sort_len -= 1
            else:
                now = A.popleft()
            print(now)

        else:
            # sort_len += len(A)
            for a in A:
                heapq.heappush(B, a)
            A = deque([])

    pass


if __name__ == '__main__':
    main()
