#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long K, std::vector<long long> a, std::vector<long long> t){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
    }
    std::vector<long long> t(K);
    for(int i = 0 ; i < K ; i++){
        scanf("%lld",&t[i]);
    }
    solve(N, K, std::move(a), std::move(t));
    return 0;
}
