#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, C: "List[int]"):
    C.sort()
    ans = C[0]

    for i in range(1, N):
        ans *= C[i]-i
        ans %= MOD
    if ans <= 0:
        print(0)
    else:
        print(ans)
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    C = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, C)


if __name__ == '__main__':
    main()
