#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def combination(n, i):
    ans = 1
    for i in range(i+1, n+1):
        ans *= i
    return ans


def solve(S: int):
    ans = 1
    if S <= 2:
        print(0)
        return
    ans = 1
    sa = 0
    n = 2
    while True:
        if S >= n*3:
            kou = S-3*n
            if S == n*3:
                ans += 1
            else:
                ans += 1+(kou*(2*(sa+1)+(kou-1)*sa))/2
        else:
            break
        sa += 1
        n += 1
        ans %= MOD
    print(int(ans) % MOD)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = int(next(tokens))  # type: int

    solve(S)


if __name__ == '__main__':
    main()
