#!/usr/bin/env python3
import sys


def solve(N: int):
    ans = []
    while N:
        if N % 2:
            ans.append('A')
            N -= 1
        else:
            ans.append('B')
            N //= 2

    ans = ans[::-1]
    print(''.join(list(map(str, ans))))
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
