#!/usr/bin/env python3
import sys


def des(li1, li2):
    return abs(li1[0]-li2[0])+abs(li1[1]-li2[1])


def solve(N: int, x: "List[int]", y: "List[int]"):
    lu = [x[0], y[0]]
    ru = [x[0], y[0]]
    ld = [x[0], y[0]]
    rd = [x[0], y[0]]
    for i in range(N):
        if x[i]
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    x = [int()] * (N)  # type: "List[int]"
    y = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))
    solve(N, x, y)


if __name__ == '__main__':
    main()
