#!/usr/bin/env python3
import sys
import math


def solve(N: int):
    # print(math.log(N, 2))
    for k in range(1000):
        if 2**k > N:
            print(k-1)
            break
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
