#include <bits/stdc++.h>
using namespace std;

const long long MOD = 998244353;

void solve(long long H, long long W, std::vector<long long> h, std::vector<long long> w){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    std::vector<long long> h(2);
    std::vector<long long> w(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&h[i]);
        scanf("%lld",&w[i]);
    }
    solve(H, W, std::move(h), std::move(w));
    return 0;
}
