#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


def solve(H: int, W: int, h: "List[int]", w: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    h = [int()] * (2)  # type: "List[int]"
    w = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        h[i] = int(next(tokens))
        w[i] = int(next(tokens))
    solve(H, W, h, w)

if __name__ == '__main__':
    main()
