#!/usr/bin/env python3
import sys


def solve(N: int, p: "List[int]"):
    Q = [0]*N
    for i in range(N):
        Q[p[i]-1] = i+1
    print(' '.join(list(map(str, Q))))
    return


# Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    p = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, p)


if __name__ == '__main__':
    main()
