#!/usr/bin/env python3
import sys


def solve(N: int, K: int, a: "List[int]"):

    so = sorted(a)
    num = K//N
    if K % N == 0:
        for i in range(N):
            print(num)
        return
    else:
        K %= N
        id = so[K-1]
    for i in range(N):

        if id < a[i]:
            print(num)
        else:
            print(num+1)

    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, a)


if __name__ == '__main__':
    main()
