#!/usr/bin/env python3
import sys

def check():
    


def solve(R: int, C: int, A: "List[List[int]]", B: "List[List[int]]"):
    dp=[[int(1e12+4)]*R for i in range(C)]
    c=0
    r=0
    while True:
        if c>0:


    for i in range()
    
    
    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    A = [[int(next(tokens)) for _ in range(C - 1)] for i in range(R)]  # type: "List[List[int]]"
    B = [[int(next(tokens)) for _ in range(C)] for i in range(R - 1)]  # type: "List[List[int]]"
    solve(R, C, A, B)

if __name__ == '__main__':
    main()
