#!/usr/bin/env python3
import sys
import math


def solve(N: int):
    ans = 0
    while True:
        if len(str(ans))*2 == len(str(N)) and int(str(ans)+str(ans)) > N:
            break

        elif len(str(ans))*2 > len(str(N)):
            break
        ans += 1
    return ans


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)


def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()

    N = int(next(tokens))  # type: int

    
    if N > 10:
        print(solve(N)-1)
    else:
        print(0)


if __name__ == '__main__':
    main()
