#!/usr/bin/env python3
import sys


def solve(N: int, S: str):

    for i in range(1, N//2+1):
        flag = False
        for j in range(N-i*2+1):
            for k in range(j+i, N-i+1):
                if S[j:j+i] == S[k:k+i]:
                    flag = True
                    break
            if flag:
                break
        if not flag:
            print(i-1)
            return
        elif i == N//2:
            print(i)
            return
    print(0)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)


if __name__ == '__main__':
    main()
