#!/usr/bin/env python3


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format

    X = list(map(int, (list(input()))))

    if len(set(X)) == 1 or ((X[0]+1) % 10 == X[1] and (X[1]+1) % 10 == X[2] and (X[2]+1) % 10 == X[3]):
        print("Weak")

    else:
        print("Strong")


if __name__ == '__main__':
    main()
