#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format

    N = int(input())
    st = [[i for i in input().split()] for _ in range(N)]

    for i in range(N-1):
        for j in range(i+1, N):
            if st[i][0] == st[j][0] and st[i][1] == st[j][1]:
                print(YES)
                exit()
    print(NO)


if __name__ == '__main__':
    main()
