#!/usr/bin/env python3
import sys


def solve(a: int, b: int, c: int):
    if a==b :
        print(c)
    elif b==c :
        print(a)
    elif a==c :
        print(b)
    else:
        print(0)


    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    c = int(next(tokens))  # type: int
    solve(a, b, c)

if __name__ == '__main__':
    main()
