
import sys


def make_divisors(n):
    odd = 0
    even = 0
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            if i % 2 == 0:
                even += 1
            else:
                odd += 1
            if i != n // i:
                if n//i % 2 == 0:
                    even += 1
                else:
                    odd += 1
                print(even)
                print(odd)
                print('')


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n = int(input())
    for j in range(n):
        i = int(input())

        if i % 2 == 1:
            print("Odd")
        elif i % 4 == 0:
            print("Even")
        else:
            print("Same")
        # make_divisors(i)


if __name__ == '__main__':
    main()
