#!/usr/bin/env python3
import sys
import collections

def solve(S: str):
    ok=set()
    ng=[]
    wh=[]

    for i in range(10):
        if S[i]=='o':
            ok.add(str(i))
        elif S[i]=='x':
            ng.append(i)
        else:
            wh.append(i)


    if len(ok)==5 :
        print(0)
        return 
    if ok==4:
        print(4*3*2)
        return 

    ans=0
    num=[str(i) for i in range(10)]
    for s1 in num:
        for s2 in num:
            for s3 in num:
                for s4 in num:
                    s=[s1,s2,s3,s4]
                    if set(s) >= set(ok) :
                        
                        if [1 for j in s if int(j) in ng]  :
                            continue
                        ans+=1
        
    print(ans)
    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
