#!/usr/bin/env python3
import math

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)


def main():
    n = int(input())
    x0, y0 = map(int, input().split())
    x2n, y2n = map(int, input().split())

    centerx = (x2n-x0)/2+x0
    centery = (y2n-y0)/2 + y0
    len = math.sqrt((x2n-x0)**2+(y2n-y0)**2)
    p = complex(x0, y0)
    p1 = complex(centerx, centery)
    point = p-p1

    rot = complex(math.cos(2*math.pi/n), math.sin(2*math.pi/n))

    point *= rot
    ans = point + p1
    print(f'{ans.real} {ans.imag}')

# Failed to predict input format


if __name__ == '__main__':
    main()
