#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    li=[0]*200
    ans=0
    for i in range(N):
        ans+=li[(A[i]%200)]
        li[(A[i]%200)]+=1
        
    print(ans)

    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
