#!/usr/bin/env python3
import sys
import math


def solve(R: int, X: int, Y: int):
    r = math.sqrt(X**2+Y**2)
    if r < R:
        print(2)
        return
    elif r % R == 0:
        print(int(r//R))
        return
    else:
        print(int(r//R)+1)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    solve(R, X, Y)


if __name__ == '__main__':
    main()
