#!/usr/bin/env python3
import sys


def solve(N: int, K: int):
    dp=[0]*(3*N+3)   #dp[score]=count berow
    dp[3]=1
    now=3
    while dp[now]<K:
        if now<=N-2:
            dp[now+1]=dp[now]+now-1
        else:
            
    
        




    return


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
