#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int):
    front = 0
    back = 0
    a = []
    flag = True
    for i in range(len(N)):
        if N[i] == '0':
            front += 1
        else:
            break

    for i in reversed(range(len(N))):
        if N[i] == '0':
            back += 1
        else:
            break

    if front > back:
        print('No')
    else:
        for i in range(len(N)):
            if front <= len(N)-back-1:
                if N[front] == N[len(N)-back-1]:
                    pass
                else:
                    print('No')
                    return
            else:
                print('Yes')
                return
            front += 1
            back += 1

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = (next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
