#!/usr/bin/env python3
import sys


def solve(P: int):
    ans = 0

    while P:
        monney = 1
        for i in range(1, 100000):
            if P < monney*i:
                P -= monney
                ans += 1
                break
            else:
                monney *= i
    print(ans)
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    P = int(next(tokens))  # type: int
    solve(P)


if __name__ == '__main__':
    main()
